name: sadasbor_v2
description: "A New Look of Sadasbor"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  analyzer: ^7.5.1                               # A versatile package for efficient code analysis in Flutter projects.
  auto_route: ^10.1.0+1                             # A Flutter routing library that generates route code.
  calendar_date_picker2: ^2.0.1                  # A calendar date picker widget for selecting dates.
  connectivity_plus: ^6.0.3                      # Allows you to monitor network connectivity in Flutter.
  dartz: ^0.10.1                                 # A functional programming library for Dart.
  dio: ^5.4.3+1                                    # A powerful HTTP client for making network requests in Flutter.
  dio_cookie_manager: ^3.1.1                     # Cookie manager for Dio HTTP client in Flutter.
  get_it: ^8.0.3                                 # A service locator for Flutter.
  injectable: ^2.4.2                             # Dependency injection for Flutter and Dart.
  flutter_native_splash: ^2.4.0                  # Generate native splash screens for Flutter apps.
  flutter_bloc: ^9.1.1                           # Implements the BLoC pattern for state management in Flutter.
  freezed: ^3.0.6                                # Code generation for immutable classes in Dart/Flutter.
  flutter_hooks: ^0.21.2                         # Flutter hooks for functional widget composition.
  freezed_annotation: ^3.0.0                     # Annotations for the Freezed library.
  fluttertoast: ^8.2.12                           # Show toast messages in your Flutter app.
  json_annotation: ^4.9.0                        # Code generation for JSON serialization/deserialization.
  equatable: ^2.0.5                              # Simplify equality comparisons in Dart/Flutter.
  shared_preferences: ^2.2.3                     # Persistent key-value storage for Flutter.
  hydrated_bloc: ^10.0.0                          # Flutter BLoC state persistence with HydratedBloc.
  pretty_dio_logger: ^1.3.1                      # Pretty logs for the Dio HTTP client in Flutter.
  pull_to_refresh: ^2.0.0                        # Add pull-to-refresh functionality to Flutter views.
  package_info_plus: ^8.0.2                      # Access package information in Flutter.
  intl: ^0.20.2                                  # Internationalization and localization for Flutter.
  google_fonts: ^6.2.1                           # Use Google Fonts in your Flutter app.
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.10+1                            # Render SVG files in Flutter apps.
  cached_network_image: ^3.4.1
  # Html Dependencies
  flutter_html: ^3.0.0
  html: ^0.15.6
  infinite_scroll_pagination: ^5.1.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  syncfusion_flutter_charts: ^30.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.1.0               # A code generator for AutoRoute, a Flutter routing library.
  build_runner: ^2.5.4                       # A build system for generating Dart code in your Flutter project.
  flutter_launcher_icons: ^0.14.4            # A tool to generate launcher icons for your Flutter app.
  flutter_lints: ^6.0.0                      # A set of lint rules for Dart and Flutter projects.
  flutter_secure_storage: ^9.2.2             # A Flutter plugin for securely storing sensitive data.
  injectable_generator: ^2.7.0               # A code generator for the Injectable dependency injection library in Flutter.
  json_serializable: ^6.9.5                  # A code generation library for JSON serialization and deserialization in Dart/Flutter.
  pubspec_dependency_sorter: ^1.0.4          # A utility for sorting dependencies in your Flutter `pubspec.yaml` file.
  retrofit_generator: ^9.2.0                # A code generator for Retrofit, a type-safe HTTP client for Dart/Flutter.
  path_provider: ^2.1.3                          # Get filesystem paths in Flutter.

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/icon/icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/icon/icon.png
  android_12:
    color: '#FFFFFF'
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icon/
    - assets/logo/
  # Untuk menambahkan font khusus ke aplikasi Anda, tambahkan bagian font di sini.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
